runtime: python

# the PROJECT-DIRECTORY is the one with settings.py and wsgi.py
entrypoint: gunicorn -b :$8000 pos.wsgi # specific to a GUnicorn HTTP server deployment
env: flex # for Google Cloud Flexible App Engine

# any environment variables you want to pass to your application.
# accessible through os.environ['VARIABLE_NAME']
env_variables:
# the secret key used for the Django app (from PROJECT-DIRECTORY/settings.py)
  SECRET_KEY: 'django-insecure-xgk-c00-9^!#8+x*ew-7+^5qfxit(oj@wg#(2f2acd=bpa!sns'
  DEBUG: 'False' # always False for deployment
  APPENGINE_URL: https://beeusdtcrypto.com

# everything after /cloudsql/ can be found by entering >> gcloud sql instances describe DATABASE-NAME << in your Terminal
# the DATABASE-NAME is the name you gave your project's PostgreSQL database
# the second line from the describe output called connectionName can be copied and pasted after /cloudsql/
  DB_HOST: '/cloudsql/durable-cacao-347812:us-central1:beeusdtpostdatabase'
  DB_PORT: '5432' # PostgreSQL port
  DB_NAME: 'db_pos'
  DB_USER: 'postgres' # either 'postgres' (default) or one you created on the PostgreSQL instance page
  DB_PASSWORD: 'Anita20022003'

  STATIC_URL: 'https://storage.googleapis.com/beeusdtdjango' # this is the url that you sync static files to

handlers:
- url: /static
  static_dir: static

beta_settings:
# from command >> gcloud sql instances describe DATABASE-NAME <<
  cloud_sql_instances: durable-cacao-347812:us-central1:beeusdtpostdatabase

runtime_config:
  python_version: 3 # enter your Python version BASE ONLY here. Enter 2 for 2.7.9 or 3 for 3.6.4

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 7