# Generated by Django 4.0.3 on 2022-04-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_withdraws_date_and_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposits',
            name='wallet_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
