# Generated by Django 4.0.3 on 2022-04-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_first_gen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
    ]
