# Generated by Django 4.0.3 on 2022-04-18 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_gen',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='second_gen',
        ),
    ]
