# Generated by Django 4.0.3 on 2022-04-18 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_userprofile_first_gen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='first_gen',
            field=models.ManyToManyField(blank=True, default=None, related_name='first_gen', to=settings.AUTH_USER_MODEL),
        ),
    ]
