# Generated by Django 4.0.3 on 2022-04-18 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_userprofile_first_gen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral', to=settings.AUTH_USER_MODEL),
        ),
    ]
