# Generated by Django 4.0.3 on 2022-04-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_text', models.TextField(max_length=1800)),
                ('withdrawal_text', models.TextField(max_length=1800)),
                ('withdrawal_charge', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('about_us', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
