# Generated by Django 4.0.3 on 2022-04-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='withdrawal_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
