# Generated by Django 4.0.3 on 2022-04-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_settings_withdrawal_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='daily_earning',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
