# Generated by Django 4.0.3 on 2022-04-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_settings_daily_earning'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='first_gen_referral',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='settings',
            name='second_gen_referral',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
