# Generated by Django 4.0.3 on 2022-04-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_walletaddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='walletaddress',
            options={'verbose_name_plural': 'Wallet Address'},
        ),
        migrations.RemoveField(
            model_name='settings',
            name='about_us',
        ),
    ]
