# Generated by Django 4.0.3 on 2022-04-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_walletaddress_options_remove_settings_about_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutUs', models.TextField(max_length=2000)),
                ('whyYouCanTrustUs', models.TextField(max_length=1800)),
                ('ourMission', models.TextField(max_length=1800)),
            ],
            options={
                'verbose_name_plural': 'About US Page',
            },
        ),
    ]
