# Generated by Django 4.0.3 on 2022-04-20 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_aboutuspage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutuspage',
            old_name='aboutUs',
            new_name='about_us_section',
        ),
        migrations.RenameField(
            model_name='aboutuspage',
            old_name='ourMission',
            new_name='our_mission_section',
        ),
        migrations.RenameField(
            model_name='aboutuspage',
            old_name='whyYouCanTrustUs',
            new_name='why_you_can_trust_us_section',
        ),
    ]
