# Generated by Django 3.2.13 on 2022-04-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_aboutus_aboutuspage_about_us_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletaddress',
            name='type',
            field=models.CharField(choices=[('USDT(TRC20)', 'USDT(TRC20)'), ('USDT(Bep20)', 'USDT(Bep20)')], max_length=30, null=True),
        ),
    ]
